"""add city to residential complexes

Revision ID: 80fa48382949
Revises: 8acc4dda3b1f
Create Date: 2025-06-25 16:17:22.159845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fa48382949'
down_revision: Union[str, None] = '8acc4dda3b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_complexes', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residential_complexes', 'city')
    # ### end Alembic commands ###
